// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package registry_terraform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Discovery struct {
	ProvidersV1          string   `protobuf:"bytes,1,opt,name=ProvidersV1,json=providers.v1,proto3" json:"ProvidersV1,omitempty"`
	ModulesV1            string   `protobuf:"bytes,2,opt,name=ModulesV1,json=modules.v1,proto3" json:"ModulesV1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discovery) Reset()         { *m = Discovery{} }
func (m *Discovery) String() string { return proto.CompactTextString(m) }
func (*Discovery) ProtoMessage()    {}
func (*Discovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *Discovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discovery.Unmarshal(m, b)
}
func (m *Discovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discovery.Marshal(b, m, deterministic)
}
func (m *Discovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discovery.Merge(m, src)
}
func (m *Discovery) XXX_Size() int {
	return xxx_messageInfo_Discovery.Size(m)
}
func (m *Discovery) XXX_DiscardUnknown() {
	xxx_messageInfo_Discovery.DiscardUnknown(m)
}

var xxx_messageInfo_Discovery proto.InternalMessageInfo

func (m *Discovery) GetProvidersV1() string {
	if m != nil {
		return m.ProvidersV1
	}
	return ""
}

func (m *Discovery) GetModulesV1() string {
	if m != nil {
		return m.ModulesV1
	}
	return ""
}

type Platform struct {
	OperatingSystem      string   `protobuf:"bytes,1,opt,name=OperatingSystem,json=os,proto3" json:"OperatingSystem,omitempty"`
	Architecture         string   `protobuf:"bytes,2,opt,name=Architecture,json=arch,proto3" json:"Architecture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Platform) Reset()         { *m = Platform{} }
func (m *Platform) String() string { return proto.CompactTextString(m) }
func (*Platform) ProtoMessage()    {}
func (*Platform) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *Platform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Platform.Unmarshal(m, b)
}
func (m *Platform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Platform.Marshal(b, m, deterministic)
}
func (m *Platform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Platform.Merge(m, src)
}
func (m *Platform) XXX_Size() int {
	return xxx_messageInfo_Platform.Size(m)
}
func (m *Platform) XXX_DiscardUnknown() {
	xxx_messageInfo_Platform.DiscardUnknown(m)
}

var xxx_messageInfo_Platform proto.InternalMessageInfo

func (m *Platform) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *Platform) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

type ProviderVersionListEntry struct {
	Version              string      `protobuf:"bytes,1,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Protocols            []string    `protobuf:"bytes,2,rep,name=Protocols,json=protocols,proto3" json:"Protocols,omitempty"`
	Platforms            []*Platform `protobuf:"bytes,3,rep,name=Platforms,json=platforms,proto3" json:"Platforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProviderVersionListEntry) Reset()         { *m = ProviderVersionListEntry{} }
func (m *ProviderVersionListEntry) String() string { return proto.CompactTextString(m) }
func (*ProviderVersionListEntry) ProtoMessage()    {}
func (*ProviderVersionListEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *ProviderVersionListEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderVersionListEntry.Unmarshal(m, b)
}
func (m *ProviderVersionListEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderVersionListEntry.Marshal(b, m, deterministic)
}
func (m *ProviderVersionListEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderVersionListEntry.Merge(m, src)
}
func (m *ProviderVersionListEntry) XXX_Size() int {
	return xxx_messageInfo_ProviderVersionListEntry.Size(m)
}
func (m *ProviderVersionListEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderVersionListEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderVersionListEntry proto.InternalMessageInfo

func (m *ProviderVersionListEntry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ProviderVersionListEntry) GetProtocols() []string {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *ProviderVersionListEntry) GetPlatforms() []*Platform {
	if m != nil {
		return m.Platforms
	}
	return nil
}

type ProviderVersionList struct {
	ID                   string                      `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Versions             []*ProviderVersionListEntry `protobuf:"bytes,2,rep,name=Versions,json=versions,proto3" json:"Versions,omitempty"`
	Warnings             []string                    `protobuf:"bytes,3,rep,name=Warnings,json=warnings,proto3" json:"Warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ProviderVersionList) Reset()         { *m = ProviderVersionList{} }
func (m *ProviderVersionList) String() string { return proto.CompactTextString(m) }
func (*ProviderVersionList) ProtoMessage()    {}
func (*ProviderVersionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *ProviderVersionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderVersionList.Unmarshal(m, b)
}
func (m *ProviderVersionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderVersionList.Marshal(b, m, deterministic)
}
func (m *ProviderVersionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderVersionList.Merge(m, src)
}
func (m *ProviderVersionList) XXX_Size() int {
	return xxx_messageInfo_ProviderVersionList.Size(m)
}
func (m *ProviderVersionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderVersionList.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderVersionList proto.InternalMessageInfo

func (m *ProviderVersionList) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProviderVersionList) GetVersions() []*ProviderVersionListEntry {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *ProviderVersionList) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type ProviderVersion struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,json=owner,proto3" json:"Owner,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=Namespace,json=namespace,proto3" json:"Namespace,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Alias                string   `protobuf:"bytes,5,opt,name=Alias,json=alias,proto3" json:"Alias,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Tag                  string   `protobuf:"bytes,7,opt,name=Tag,json=tag,proto3" json:"Tag,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Source               string   `protobuf:"bytes,9,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
	PublishedAt          string   `protobuf:"bytes,10,opt,name=PublishedAt,json=published_at,proto3" json:"PublishedAt,omitempty"`
	Downloads            int64    `protobuf:"varint,11,opt,name=Downloads,json=downloads,proto3" json:"Downloads,omitempty"`
	Tier                 string   `protobuf:"bytes,12,opt,name=Tier,json=tier,proto3" json:"Tier,omitempty"`
	Versions             []string `protobuf:"bytes,13,rep,name=Versions,json=versions,proto3" json:"Versions,omitempty"`
	Docs                 []string `protobuf:"bytes,14,rep,name=Docs,json=docs,proto3" json:"Docs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderVersion) Reset()         { *m = ProviderVersion{} }
func (m *ProviderVersion) String() string { return proto.CompactTextString(m) }
func (*ProviderVersion) ProtoMessage()    {}
func (*ProviderVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *ProviderVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderVersion.Unmarshal(m, b)
}
func (m *ProviderVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderVersion.Marshal(b, m, deterministic)
}
func (m *ProviderVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderVersion.Merge(m, src)
}
func (m *ProviderVersion) XXX_Size() int {
	return xxx_messageInfo_ProviderVersion.Size(m)
}
func (m *ProviderVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderVersion proto.InternalMessageInfo

func (m *ProviderVersion) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProviderVersion) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ProviderVersion) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ProviderVersion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProviderVersion) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *ProviderVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ProviderVersion) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ProviderVersion) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProviderVersion) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ProviderVersion) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

func (m *ProviderVersion) GetDownloads() int64 {
	if m != nil {
		return m.Downloads
	}
	return 0
}

func (m *ProviderVersion) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *ProviderVersion) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *ProviderVersion) GetDocs() []string {
	if m != nil {
		return m.Docs
	}
	return nil
}

type GPGPublicKeys struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=KeyID,json=key_id,proto3" json:"KeyID,omitempty"`
	AsciiArmor           string   `protobuf:"bytes,2,opt,name=AsciiArmor,json=ascii_armor,proto3" json:"AsciiArmor,omitempty"`
	TrustSignature       string   `protobuf:"bytes,3,opt,name=TrustSignature,json=trust_signature,proto3" json:"TrustSignature,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
	SourceURL            string   `protobuf:"bytes,5,opt,name=SourceURL,json=source_url,proto3" json:"SourceURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPGPublicKeys) Reset()         { *m = GPGPublicKeys{} }
func (m *GPGPublicKeys) String() string { return proto.CompactTextString(m) }
func (*GPGPublicKeys) ProtoMessage()    {}
func (*GPGPublicKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *GPGPublicKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPGPublicKeys.Unmarshal(m, b)
}
func (m *GPGPublicKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPGPublicKeys.Marshal(b, m, deterministic)
}
func (m *GPGPublicKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPGPublicKeys.Merge(m, src)
}
func (m *GPGPublicKeys) XXX_Size() int {
	return xxx_messageInfo_GPGPublicKeys.Size(m)
}
func (m *GPGPublicKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_GPGPublicKeys.DiscardUnknown(m)
}

var xxx_messageInfo_GPGPublicKeys proto.InternalMessageInfo

func (m *GPGPublicKeys) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *GPGPublicKeys) GetAsciiArmor() string {
	if m != nil {
		return m.AsciiArmor
	}
	return ""
}

func (m *GPGPublicKeys) GetTrustSignature() string {
	if m != nil {
		return m.TrustSignature
	}
	return ""
}

func (m *GPGPublicKeys) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GPGPublicKeys) GetSourceURL() string {
	if m != nil {
		return m.SourceURL
	}
	return ""
}

type SigningKeys struct {
	GPGPublicKeys        []*GPGPublicKeys `protobuf:"bytes,1,rep,name=GPGPublicKeys,json=gpg_public_keys,proto3" json:"GPGPublicKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SigningKeys) Reset()         { *m = SigningKeys{} }
func (m *SigningKeys) String() string { return proto.CompactTextString(m) }
func (*SigningKeys) ProtoMessage()    {}
func (*SigningKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *SigningKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigningKeys.Unmarshal(m, b)
}
func (m *SigningKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigningKeys.Marshal(b, m, deterministic)
}
func (m *SigningKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningKeys.Merge(m, src)
}
func (m *SigningKeys) XXX_Size() int {
	return xxx_messageInfo_SigningKeys.Size(m)
}
func (m *SigningKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningKeys.DiscardUnknown(m)
}

var xxx_messageInfo_SigningKeys proto.InternalMessageInfo

func (m *SigningKeys) GetGPGPublicKeys() []*GPGPublicKeys {
	if m != nil {
		return m.GPGPublicKeys
	}
	return nil
}

type ProviderDownload struct {
	Protocols            []string     `protobuf:"bytes,1,rep,name=Protocols,json=protocols,proto3" json:"Protocols,omitempty"`
	OperatingSystem      string       `protobuf:"bytes,2,opt,name=OperatingSystem,json=os,proto3" json:"OperatingSystem,omitempty"`
	Architecture         string       `protobuf:"bytes,3,opt,name=Architecture,json=arch,proto3" json:"Architecture,omitempty"`
	Filename             string       `protobuf:"bytes,4,opt,name=Filename,json=filename,proto3" json:"Filename,omitempty"`
	DownloadURL          string       `protobuf:"bytes,5,opt,name=DownloadURL,json=download_url,proto3" json:"DownloadURL,omitempty"`
	ShasumsURL           string       `protobuf:"bytes,6,opt,name=ShasumsURL,json=shasums_url,proto3" json:"ShasumsURL,omitempty"`
	ShasumsSignatureURL  string       `protobuf:"bytes,7,opt,name=ShasumsSignatureURL,json=shasums_signature_url,proto3" json:"ShasumsSignatureURL,omitempty"`
	Shasum               string       `protobuf:"bytes,8,opt,name=Shasum,json=shasum,proto3" json:"Shasum,omitempty"`
	SigningKeys          *SigningKeys `protobuf:"bytes,9,opt,name=SigningKeys,json=signing_keys,proto3" json:"SigningKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProviderDownload) Reset()         { *m = ProviderDownload{} }
func (m *ProviderDownload) String() string { return proto.CompactTextString(m) }
func (*ProviderDownload) ProtoMessage()    {}
func (*ProviderDownload) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *ProviderDownload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderDownload.Unmarshal(m, b)
}
func (m *ProviderDownload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderDownload.Marshal(b, m, deterministic)
}
func (m *ProviderDownload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderDownload.Merge(m, src)
}
func (m *ProviderDownload) XXX_Size() int {
	return xxx_messageInfo_ProviderDownload.Size(m)
}
func (m *ProviderDownload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderDownload.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderDownload proto.InternalMessageInfo

func (m *ProviderDownload) GetProtocols() []string {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *ProviderDownload) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *ProviderDownload) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *ProviderDownload) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ProviderDownload) GetDownloadURL() string {
	if m != nil {
		return m.DownloadURL
	}
	return ""
}

func (m *ProviderDownload) GetShasumsURL() string {
	if m != nil {
		return m.ShasumsURL
	}
	return ""
}

func (m *ProviderDownload) GetShasumsSignatureURL() string {
	if m != nil {
		return m.ShasumsSignatureURL
	}
	return ""
}

func (m *ProviderDownload) GetShasum() string {
	if m != nil {
		return m.Shasum
	}
	return ""
}

func (m *ProviderDownload) GetSigningKeys() *SigningKeys {
	if m != nil {
		return m.SigningKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "registry.terraform.Empty")
	proto.RegisterType((*Discovery)(nil), "registry.terraform.Discovery")
	proto.RegisterType((*Platform)(nil), "registry.terraform.Platform")
	proto.RegisterType((*ProviderVersionListEntry)(nil), "registry.terraform.ProviderVersionListEntry")
	proto.RegisterType((*ProviderVersionList)(nil), "registry.terraform.ProviderVersionList")
	proto.RegisterType((*ProviderVersion)(nil), "registry.terraform.ProviderVersion")
	proto.RegisterType((*GPGPublicKeys)(nil), "registry.terraform.GPGPublicKeys")
	proto.RegisterType((*SigningKeys)(nil), "registry.terraform.SigningKeys")
	proto.RegisterType((*ProviderDownload)(nil), "registry.terraform.ProviderDownload")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xae, 0x2c, 0xff, 0x48, 0x23, 0xaf, 0xbd, 0xe0, 0x76, 0x0b, 0x75, 0xbb, 0x41, 0x1c, 0x5d,
	0xea, 0x43, 0x61, 0x20, 0xee, 0xad, 0x37, 0xb7, 0x4e, 0xd3, 0x34, 0x49, 0x63, 0xc8, 0x69, 0xda,
	0x9b, 0xc1, 0x48, 0x8c, 0x4c, 0x44, 0x16, 0x05, 0x92, 0x76, 0xa0, 0x67, 0x28, 0xd0, 0xd7, 0xe8,
	0x33, 0xf5, 0x15, 0xfa, 0x14, 0x05, 0x49, 0xd1, 0x8e, 0x13, 0xe7, 0x38, 0xdf, 0x7c, 0x1e, 0xcd,
	0x7c, 0xdf, 0x47, 0x43, 0x8f, 0x93, 0x8c, 0x0a, 0xc9, 0xab, 0x51, 0xc9, 0x99, 0x64, 0x08, 0x6d,
	0x6b, 0x49, 0x38, 0xc7, 0x0f, 0x8c, 0xaf, 0xa2, 0x0e, 0xb4, 0xce, 0x56, 0xa5, 0xac, 0xa2, 0x6b,
	0xf0, 0xa7, 0x54, 0x24, 0x6c, 0x43, 0x78, 0x85, 0x4e, 0x20, 0x98, 0x71, 0xb6, 0xa1, 0x29, 0xe1,
	0xe2, 0xee, 0x34, 0x74, 0x06, 0xce, 0xd0, 0x8f, 0xbb, 0xa5, 0x85, 0x46, 0x9b, 0x53, 0x74, 0x04,
	0xfe, 0x35, 0x4b, 0xd7, 0x39, 0x51, 0x84, 0x86, 0x26, 0xc0, 0xca, 0x00, 0xa3, 0xcd, 0x69, 0xf4,
	0x13, 0x78, 0xb3, 0x1c, 0x4b, 0xf5, 0x0d, 0xf4, 0x0d, 0xf4, 0x6f, 0x4a, 0xc2, 0xb1, 0xa4, 0x45,
	0x36, 0xaf, 0x84, 0x24, 0xab, 0x7a, 0x62, 0x83, 0x09, 0xf4, 0x09, 0xba, 0x13, 0x9e, 0x2c, 0xa9,
	0x24, 0x89, 0x5c, 0x73, 0x52, 0x8f, 0x6a, 0x62, 0x9e, 0x2c, 0xa3, 0xbf, 0x1d, 0x08, 0xed, 0x1e,
	0x77, 0x84, 0x0b, 0xca, 0x8a, 0x2b, 0x2a, 0xe4, 0x59, 0x21, 0x79, 0x85, 0x42, 0xe8, 0xd4, 0x58,
	0x3d, 0xad, 0xb3, 0x31, 0x25, 0xfa, 0x0c, 0xfe, 0x4c, 0x1d, 0x9c, 0xb0, 0x5c, 0x84, 0x8d, 0x81,
	0x3b, 0xf4, 0x63, 0xbf, 0xb4, 0x00, 0xfa, 0x01, 0x7c, 0xbb, 0x99, 0x08, 0xdd, 0x81, 0x3b, 0x0c,
	0xc6, 0x9f, 0x47, 0xaf, 0x95, 0x19, 0x59, 0x52, 0xec, 0x97, 0x96, 0x1e, 0xfd, 0xe5, 0xc0, 0x87,
	0x03, 0x0b, 0xa1, 0x1e, 0x34, 0x2e, 0xa6, 0xf6, 0x28, 0x9a, 0xa2, 0x5f, 0xc0, 0xab, 0xdb, 0x66,
	0x81, 0x60, 0xfc, 0xdd, 0xc1, 0x4f, 0xbc, 0x71, 0x5b, 0xec, 0xd5, 0xa7, 0x28, 0x79, 0xbc, 0x3f,
	0x30, 0x2f, 0x68, 0x91, 0x99, 0x65, 0xfd, 0xd8, 0x7b, 0xaa, 0xeb, 0xe8, 0xbf, 0x06, 0xf4, 0x5f,
	0x8c, 0x78, 0xb5, 0xc9, 0x97, 0xd0, 0xba, 0x79, 0x2a, 0x08, 0xaf, 0x75, 0x6d, 0x31, 0x55, 0x28,
	0x85, 0x7e, 0xc3, 0x2b, 0x22, 0x4a, 0x9c, 0x90, 0xd0, 0xd5, 0x1d, 0xbf, 0xb0, 0x00, 0x42, 0xd0,
	0x54, 0xdd, 0xb0, 0x69, 0xac, 0x50, 0x0d, 0x35, 0x67, 0x92, 0x53, 0x2c, 0xc2, 0x96, 0x99, 0x83,
	0x55, 0xf1, 0xdc, 0x83, 0xf6, 0xbe, 0x07, 0xef, 0xc1, 0xbd, 0xc5, 0x59, 0xd8, 0xd1, 0xa8, 0x2b,
	0x71, 0x86, 0x06, 0x10, 0x4c, 0x89, 0x48, 0x38, 0x2d, 0xa5, 0xe2, 0x7b, 0xba, 0x13, 0xa4, 0x3b,
	0x08, 0x7d, 0x05, 0xed, 0x39, 0x5b, 0xf3, 0x84, 0x84, 0xbe, 0x6e, 0xb6, 0x85, 0xae, 0x74, 0x1a,
	0xd7, 0xf7, 0x39, 0x15, 0x4b, 0x92, 0x4e, 0x64, 0x08, 0x75, 0x1a, 0x2d, 0xb4, 0xc0, 0x52, 0x1d,
	0x34, 0x65, 0x4f, 0x45, 0xce, 0x70, 0x2a, 0xc2, 0x60, 0xe0, 0x0c, 0xdd, 0xd8, 0x4f, 0x2d, 0xa0,
	0x0e, 0xba, 0xa5, 0x84, 0x87, 0x5d, 0x73, 0x90, 0xa4, 0x84, 0x2b, 0x61, 0xb7, 0x16, 0xbd, 0x33,
	0xc2, 0x6e, 0x45, 0x47, 0xd0, 0x9c, 0xb2, 0x44, 0x84, 0x3d, 0x8d, 0x37, 0x53, 0x96, 0x88, 0xe8,
	0x1f, 0x07, 0xde, 0x9d, 0xcf, 0xce, 0xf5, 0x22, 0xc9, 0x25, 0xa9, 0x04, 0xfa, 0x08, 0xad, 0x4b,
	0x52, 0x6d, 0xd5, 0x6e, 0x3f, 0x92, 0x6a, 0x41, 0x53, 0x74, 0x0c, 0x30, 0x11, 0x09, 0xa5, 0x13,
	0xbe, 0x62, 0x56, 0xf6, 0x00, 0x2b, 0x64, 0x81, 0x15, 0x84, 0xbe, 0x85, 0xde, 0x2d, 0x5f, 0x0b,
	0x39, 0xa7, 0x59, 0x81, 0x75, 0xe6, 0x8d, 0x03, 0x7d, 0xa9, 0xd0, 0x85, 0xb0, 0xf0, 0x33, 0x3d,
	0x9a, 0x7b, 0x7a, 0x1c, 0x81, 0x6f, 0xf0, 0xdf, 0xe3, 0xab, 0xda, 0x0f, 0x30, 0xad, 0xc5, 0x9a,
	0xe7, 0xd1, 0x9f, 0x10, 0xa8, 0xd1, 0xb4, 0xc8, 0xf4, 0x9a, 0x17, 0x2f, 0xf6, 0x0e, 0x1d, 0x1d,
	0xc8, 0x93, 0x43, 0x81, 0xdc, 0x23, 0xc6, 0xfd, 0xac, 0xcc, 0x16, 0x5a, 0xe6, 0x64, 0xf1, 0x48,
	0x2a, 0x11, 0xfd, 0xdb, 0x80, 0xf7, 0x36, 0x70, 0x56, 0xee, 0xfd, 0xd7, 0xe6, 0xbc, 0x7c, 0x6d,
	0x07, 0xde, 0x7e, 0xe3, 0xcd, 0xb7, 0xef, 0xee, 0xde, 0xbe, 0xf2, 0xe7, 0x67, 0x9a, 0x93, 0x62,
	0x17, 0x44, 0xef, 0xa1, 0xae, 0x55, 0x20, 0xec, 0xe7, 0x77, 0x12, 0x74, 0xad, 0xdf, 0x4a, 0x04,
	0xe5, 0xc2, 0x7c, 0x89, 0xc5, 0x7a, 0x25, 0x14, 0xc3, 0x84, 0x33, 0x10, 0x06, 0xd1, 0x84, 0x31,
	0x7c, 0xa8, 0x09, 0x5b, 0x1f, 0x14, 0xd3, 0x04, 0xf6, 0xa3, 0x65, 0x6e, 0xcd, 0xd0, 0xbf, 0x51,
	0x86, 0xe8, 0x46, 0x9d, 0xde, 0xb6, 0xa1, 0xa1, 0x1f, 0xf7, 0x14, 0xd7, 0xe9, 0x0d, 0xc6, 0xc7,
	0x87, 0x04, 0x7e, 0x46, 0x8b, 0xbb, 0xc2, 0x14, 0x5a, 0xdb, 0xf1, 0x1d, 0x78, 0x71, 0xcd, 0x47,
	0xbf, 0x42, 0xf7, 0x9c, 0xc8, 0xdd, 0xdf, 0xf1, 0xd7, 0x87, 0x46, 0xe9, 0xbf, 0xed, 0x4f, 0x47,
	0x87, 0x5a, 0xdb, 0x5f, 0x46, 0x5f, 0xdc, 0xb7, 0xb5, 0x17, 0xdf, 0xff, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0xc1, 0x95, 0x01, 0x0d, 0x06, 0x00, 0x00,
}
